// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7IMQLWH37k0mxMLXkqw1FCIJBbDIzc3k',
    appId: '1:1082663725286:web:baea72de2d92cba6777327',
    messagingSenderId: '1082663725286',
    projectId: 'chat17-e7a00',
    authDomain: 'chat17-e7a00.firebaseapp.com',
    storageBucket: 'chat17-e7a00.appspot.com',
    measurementId: 'G-10K8ZSVEMN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJkN6uxZJT9NkwBlywQkf_CKYvM3qmLoE',
    appId: '1:1082663725286:android:acb2fe353c4838fa777327',
    messagingSenderId: '1082663725286',
    projectId: 'chat17-e7a00',
    storageBucket: 'chat17-e7a00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiYBj1Js1lyoge8dlImtQyBBp7WMbE2_o',
    appId: '1:1082663725286:ios:98dbeeb02b288b6e777327',
    messagingSenderId: '1082663725286',
    projectId: 'chat17-e7a00',
    storageBucket: 'chat17-e7a00.appspot.com',
    androidClientId: '1082663725286-p8kocq10o7n8jd25q8qaflp9cbn49cia.apps.googleusercontent.com',
    iosClientId: '1082663725286-qkk8t46u9kp4v3t32hdqemmqiub450ck.apps.googleusercontent.com',
    iosBundleId: 'chat17-e7a00',
  );
}
